<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Class Name</name>
   <tag></tag>
   <elementGuidId>0c8391b7-ae43-412a-8f0e-f7cd713d1801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-48</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-48']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb0ce849-6665-4cec-819d-00edcfa48c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>14b62322-bbe3-4b5d-a6f7-9b2ea6d62a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>e5994bbd-d3ab-4300-b041-77abd0bb48ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-48</value>
      <webElementGuid>657712b8-34ff-42e9-8d09-dc941e8178ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20db2977-98b6-40eb-9de0-f4c56072d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-48&quot;)</value>
      <webElementGuid>e27ac73b-1b8f-476e-935e-f1b24b585424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-48']</value>
      <webElementGuid>f574a472-1e00-477c-bbb0-ea153474f75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>ae97d09f-1919-45f1-ac77-15102ad13445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d7c8d847-fb36-45b1-9dd5-008407e68cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-48' and @type = 'text']</value>
      <webElementGuid>8af81066-33f9-45fe-b212-c8eba72501e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
