<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Author</name>
   <tag></tag>
   <elementGuidId>4c5e72cd-c87f-4d0c-a397-b96d16a16aa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-87</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-87']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>595e0bb0-f6e0-4f45-92f1-7d3d155bf47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-87</value>
      <webElementGuid>8df13c85-14a0-4cd8-ae9b-1feed719207c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>027fc9e1-c4bc-450d-b89c-be834fbda5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-87&quot;)</value>
      <webElementGuid>e6e7db5a-bb2c-42f3-b69d-65b8a09406f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-87']</value>
      <webElementGuid>09faf25b-60e8-4605-ab3e-436cf2f0dcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[4]/div/div/div/div/input</value>
      <webElementGuid>64ef9584-3cd9-418d-8a3a-5519d72cc306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>507b4b73-0e1f-4452-b84a-a519f75903ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-87' and @type = 'text']</value>
      <webElementGuid>2f5f6345-2aa8-4755-ae56-6f6a31fa728c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
