<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category</name>
   <tag></tag>
   <elementGuidId>a7cb17b6-fa5e-4b9a-acc7-3d358e4e241d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-81</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-81']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f483bdae-9944-4ef0-8d02-0133e848dd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-81</value>
      <webElementGuid>e7a1d4c1-465f-4fb5-af43-22e33bbf8777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b484a429-c2bd-4087-8574-535d689c6b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-81&quot;)</value>
      <webElementGuid>56256d34-f736-4ab9-a419-a93ccc25f8b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-81']</value>
      <webElementGuid>a7ff56d0-257e-45d1-816c-80bdf18f858f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>ef649111-cd24-4494-96ca-59cf52f82637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>416052eb-2a65-4f32-83ca-7b7407cf0389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-81' and @type = 'text']</value>
      <webElementGuid>63127551-217f-4989-8502-c6b33a2df71b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
