<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date</name>
   <tag></tag>
   <elementGuidId>d712e52b-889b-4b8d-886b-690945e76e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-90</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-90']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f71647b-5047-4ca0-be3e-f2e1e24a20f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-90</value>
      <webElementGuid>cf8388fb-ee70-4319-ba8e-ec11f3266eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbcf4eca-fa81-4c68-aeea-6db5216c9d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-90&quot;)</value>
      <webElementGuid>fed6a6ad-e725-4ea6-9961-332c532c8be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-90']</value>
      <webElementGuid>2fc3ad80-5eac-4cdf-a2d2-e10486291399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[5]/div/div/div/div/input</value>
      <webElementGuid>6d1147b4-ef5c-4152-a888-4af4cec179c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>04b4d8d2-cea3-4abe-97ad-19384d7f60cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-90' and @type = 'text']</value>
      <webElementGuid>cdebc37e-faa1-473d-b131-43b0efbda4f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
