<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title</name>
   <tag></tag>
   <elementGuidId>137d257e-ff66-45a5-b72e-01efa365f236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-84</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-84']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8bb3562-d414-4153-bfe0-e97fd6584c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-84</value>
      <webElementGuid>a170977d-fe3a-49d1-8328-94f40aa1c68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>345000a1-b27a-442d-86cd-e2c392131548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-84&quot;)</value>
      <webElementGuid>6e02027b-f48c-41d3-97e6-efd132c6dac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-84']</value>
      <webElementGuid>b9bd81a4-a383-4b31-9da1-54f9581b7ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>710bae36-9c80-4478-afe1-1e77da8d596f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>0cfc5525-884b-48b9-a42d-4a8f2f57b66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-84' and @type = 'text']</value>
      <webElementGuid>c491beff-b705-475f-a7d5-f6c31f122b01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
