<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <elementGuidId>0dddff40-cea7-489a-bc0a-154bf64efd4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-116</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-116']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e14fc974-8f05-4ff9-83f1-0dfe51459c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-116</value>
      <webElementGuid>949c7d88-fe0e-4f49-9571-9d007b3df9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>921d6b5f-4fb9-4b2c-bf51-b408c23c3c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-116&quot;)</value>
      <webElementGuid>bf461ce9-3250-4172-8423-1b72ee5ed8b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-116']</value>
      <webElementGuid>e0e33b33-2f14-45a7-b11d-141b36a5c93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>327d8882-6698-4a33-ac86-f8446dc1ff30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>85c6a535-c8e1-4d0c-8b37-e9ceb5308aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-116' and @type = 'text']</value>
      <webElementGuid>3dcd32a5-c4bb-4602-836a-0e1e566cc59e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
