<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Class Name</name>
   <tag></tag>
   <elementGuidId>d4fba8c5-a7da-4e9a-9890-db857ae33d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-48']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-48</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>950e705d-a3aa-4c1a-acd8-a0be85463b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6de9bb60-aa72-459e-9acc-5c5bd3052aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>3c61b94a-8bab-4ee6-b271-3d7a564873a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-48</value>
      <webElementGuid>5f180d6c-a673-41ec-872c-ecfa49c6955c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96351cb8-dc6c-4f19-9281-e0288c238635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-48&quot;)</value>
      <webElementGuid>a67812f3-f62c-481f-936f-4e39d2ceed5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-48']</value>
      <webElementGuid>7765a2cf-4879-4539-9fc4-3b2d54add1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>03d8b8e2-246d-426d-95c8-c7ea85dfd4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2e1b71fb-af04-48e4-9afe-26f8c859c98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-48' and @type = 'text']</value>
      <webElementGuid>f75524b8-be68-44b3-9b81-f6aad0aad7f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
