<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Class Name</name>
   <tag></tag>
   <elementGuidId>49f21b5f-dedd-4c62-8164-24cc3fb13181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-46</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-46']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8e69c96-c5d6-4a7f-b4d9-1fe3630838d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5d15d337-f513-4fa8-a0d2-bbda51f1ceea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>47455fa8-e874-4d31-a880-ea93c7e3b5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-46</value>
      <webElementGuid>22ff5c08-e82c-47ec-897d-6954721fe07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff20e333-4b5d-4bac-81c1-929559ffd95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-46&quot;)</value>
      <webElementGuid>c2027751-5906-4b17-bfef-ffada70c9fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-46']</value>
      <webElementGuid>f1e9af05-5cfb-4031-829a-85a07a31ae04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>a32ecc36-336f-4cd4-bc0f-4addefd2fdf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>648f5a45-dee1-422b-9ced-e68f12caac07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-46' and @type = 'text']</value>
      <webElementGuid>60e95454-8cfc-4231-91f0-88f650eeabbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
