<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Quota</name>
   <tag></tag>
   <elementGuidId>dbcb001d-ab5f-4d62-8035-ba154d939173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-62</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-62']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f7b146d-53f1-4953-b271-359fa2b2c40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>874dadc9-5a52-4f8b-8ca4-ce9ea206af0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>108aa0dd-5cd1-4a99-9cc3-5ce5ebdbac85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-62</value>
      <webElementGuid>079d1a90-e498-4d4b-83b8-0914e5852025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1cf71ea6-5106-48e2-ac88-2f41a9d33e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-62&quot;)</value>
      <webElementGuid>6bfe8672-1c5b-4828-a257-edf8bd44dbf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-62']</value>
      <webElementGuid>fd44b49b-40ce-4cf9-bac6-74a6d5e28c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/form/div[7]/div/div/div/input</value>
      <webElementGuid>ef405e57-3bc3-42dc-91e5-5fb3d5d33531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>b818aa31-6ccb-4592-b2c3-da528ff51bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-62' and @type = 'number']</value>
      <webElementGuid>c2055fde-15c8-455b-b1a9-12536a2b75a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
