<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search1</name>
   <tag></tag>
   <elementGuidId>b71b4788-fdda-4eac-9d08-b4941064412a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-111</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-111']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5c7bf50-8dac-441f-9848-de377fbc73f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-111</value>
      <webElementGuid>99ba35d3-fa04-4580-91d7-0826682160ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>208f5c3c-f10e-4dbd-a669-dbdbe7311211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-111&quot;)</value>
      <webElementGuid>91cb763b-ba90-458e-815b-4a50c4f23a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-111']</value>
      <webElementGuid>70bf2e4a-145a-4a77-a257-20e6e04783bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>aa8a39e0-87f4-4b24-9cc5-350331d7cf01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>77eaa9b0-ac4e-4ab0-9eaf-fb7eb0e69302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-111' and @type = 'text']</value>
      <webElementGuid>5f0fc736-67b4-4d36-83cd-2a242d3d05f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
