<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <elementGuidId>5e3f7f1c-ee1c-4cfd-abb8-2e08babeb9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-111</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-111']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e1c0fc7-5312-4c44-b30f-1c1cae4d8591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-111</value>
      <webElementGuid>acdb8e6f-5dbd-4c81-8b34-c3e49d271aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02c8bdd4-1db9-4ab0-8376-389692d41fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-111&quot;)</value>
      <webElementGuid>28db1169-019b-4425-8e4c-5b7517c3aabb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-111']</value>
      <webElementGuid>f1f20f45-ddbf-4297-87fb-f50a780df53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>e5ef5d8c-af62-497e-be2a-bfa805b315ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5fa8a2a8-e91b-4224-88a2-10beba6bc5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-111' and @type = 'text']</value>
      <webElementGuid>d7f8508b-5c6d-418b-814c-a104a800a0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
