<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address</name>
   <tag></tag>
   <elementGuidId>c9e4a81d-04e8-42ea-b811-c335544ce551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-101']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1d620b6-78ba-40ff-9d13-0d64b5f153d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-101</value>
      <webElementGuid>c11b735c-d188-4e96-b089-dac3bfb051b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e503474e-8f25-42b6-a434-a72c40d10c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-101&quot;)</value>
      <webElementGuid>23af0994-33fd-4776-9dec-f4258aa08904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-101']</value>
      <webElementGuid>958bd427-39d7-4563-9bfd-c215fc068887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[6]/div/div/div/div/input</value>
      <webElementGuid>b5ade438-93e9-4370-b9ed-b4cac0b775b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input</value>
      <webElementGuid>449a8f33-7c17-41e9-8c21-806ce399fe01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-101' and @type = 'text']</value>
      <webElementGuid>ac611244-85b7-4668-ab35-84ce80288afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
