<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email</name>
   <tag></tag>
   <elementGuidId>8243439e-f4d0-406b-9bdf-a8da88f12ea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-95</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-95']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d05f8af5-97df-47f0-81eb-deb3e29a5057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-95</value>
      <webElementGuid>2d216122-0445-48fd-88ca-8084da8df94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ddc5348-8530-4384-9c61-c816fa4a60c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-95&quot;)</value>
      <webElementGuid>02c3926d-db5f-4e1f-abe8-abf008feccce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-95']</value>
      <webElementGuid>9553ebfd-f241-4f2b-91c5-6b63a9f184ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[4]/div/div/div/div/input</value>
      <webElementGuid>924688ea-b812-4908-9a00-831c74e03c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>4a098fb3-05e7-4cb8-b9d2-293d55e3b3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-95' and @type = 'text']</value>
      <webElementGuid>477aa9c8-ad35-4485-8e6f-2d64c37ce693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
