<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field</name>
   <tag></tag>
   <elementGuidId>aa786fbf-e4f2-47ab-9615-caa17f1d96dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-89</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-89']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cfbae6a-15a7-4ab3-8d5c-cb67526ecc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-89</value>
      <webElementGuid>1d556b29-5450-42a2-89e6-5953d8d0078c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3030a197-0128-4351-af20-211428f23251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-89&quot;)</value>
      <webElementGuid>b0af7920-9fbd-4459-951d-2d956d5b8dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-89']</value>
      <webElementGuid>bd8a0751-885d-4af6-a575-e6157198cb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>ced9fa7d-d9aa-4286-a498-188a79569a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>8062bf41-abea-434e-aea8-2774e0f95ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-89' and @type = 'text']</value>
      <webElementGuid>32bca82b-3f21-4e23-9291-4a616adeb1a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
