<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Gender</name>
   <tag></tag>
   <elementGuidId>b554cb63-a1ff-411b-b469-d8b68fc83f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-104</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-104']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca5fb30e-2c8f-445b-b7a4-1a7f54865d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-104</value>
      <webElementGuid>0d815a60-5b0d-4527-9811-63635da304b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd72ed30-afbb-4849-9c8c-bfffe2e25dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-104&quot;)</value>
      <webElementGuid>5af22ac0-1b6f-44f0-95dc-c014963932c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-104']</value>
      <webElementGuid>dac6e00f-fb10-405f-9049-c12fda561b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[7]/div/div/div/div/input</value>
      <webElementGuid>e07adaf3-7907-4f6f-b4dc-7c0d7614c747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/input</value>
      <webElementGuid>a104cfe5-6d4e-40e7-9a3b-313764eb5706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-104' and @type = 'text']</value>
      <webElementGuid>088b2d78-f749-4947-a5ce-007702ce2a1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
