<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Name</name>
   <tag></tag>
   <elementGuidId>2c6fab57-4c25-41c0-a01f-2171594a9911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-92</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-92']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59d070fa-325c-4986-aa6e-8d76dfd070fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-92</value>
      <webElementGuid>586a2ad1-b055-402f-b143-069645529241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f336655-c667-4fee-8f63-4df36af8e148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-92&quot;)</value>
      <webElementGuid>4010a9d2-96ff-46d8-9e2d-3de2c5865dbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-92']</value>
      <webElementGuid>8230628a-1789-43a6-ae52-1f4e53307472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>b8d63029-9ccd-4d77-b936-5ec13155a424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>d41b7ea2-5a2b-4157-b88f-d998b807bd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-92' and @type = 'text']</value>
      <webElementGuid>17c70970-c437-42df-8c33-0bf47a1e8a85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
