<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phone</name>
   <tag></tag>
   <elementGuidId>b98b66b5-e6f1-4c19-93d6-11558d0bb59e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-98</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-98']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ef5b473-ee78-449b-a1d8-1867afe7572f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-98</value>
      <webElementGuid>2eb99218-25a3-47ed-851d-4c6330c371df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46980520-09e4-4391-b9dc-62e9990dd713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-98&quot;)</value>
      <webElementGuid>872e7acc-fb49-413b-806b-9f5334fad0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-98']</value>
      <webElementGuid>203c579a-77ad-4524-8d7c-9665ad15ce6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[5]/div/div/div/div/input</value>
      <webElementGuid>a652bc78-e52f-4915-bd0e-2bd985a654ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>b2d1577e-6684-4e18-a136-f2659afa122c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-98' and @type = 'text']</value>
      <webElementGuid>c82911c0-9679-4664-af35-6260b2f1fbdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
