<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <elementGuidId>59afe6b9-10c5-4457-8cab-55e944a7544f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-48']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-48</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea60c576-28b9-443a-9a5d-633213e514f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-48</value>
      <webElementGuid>557ba3ba-3de7-439d-a6b9-cd4c366fe591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>acc09760-219c-4e85-870c-e98eb309be41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-48&quot;)</value>
      <webElementGuid>ab011c00-26fb-418d-a6cf-84233d7e69f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-48']</value>
      <webElementGuid>a4603d17-da90-43f6-9bfc-82f793b0d7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>a4bccbd0-2f64-4466-840a-2f1f61170aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3c55f965-078f-4d89-b727-2bab42db04b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-48' and @type = 'text']</value>
      <webElementGuid>2ee0275a-3f4d-48e7-bcbc-36b4daf3868f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
