<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account Number</name>
   <tag></tag>
   <elementGuidId>8599a203-b52b-4be5-971e-384bd262f446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-51</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-51']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3363c3ff-0a36-4029-b9a5-fd5a59beb822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>eba96b93-3c41-4709-8475-26d3c2e97687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-51</value>
      <webElementGuid>4fb88104-523a-4f83-a8b9-26fd8bc191a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91d048da-2f06-4126-9f30-074c06788033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-51&quot;)</value>
      <webElementGuid>631f2a4a-b893-44d5-a4ab-111b83e606fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-51']</value>
      <webElementGuid>daddfc32-3e96-4a21-b4a3-5ff56e34d12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>65fb51c9-a72b-4180-8b7d-47df15c61adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>90d56784-d250-45c9-a4b0-da0e45bda4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-51' and @type = 'text']</value>
      <webElementGuid>dfcc389e-2ee2-451e-91f7-a49a2f22fadf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
