<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank Name</name>
   <tag></tag>
   <elementGuidId>942c0989-9088-4bae-aa28-d708fef74ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-48</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-48']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfbc98d8-6f38-47bf-87e8-9fc5471538bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>75aa0948-1315-417d-a0e8-2025ab2cb93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-48</value>
      <webElementGuid>2e3ef5ae-ed74-4dc4-866e-ba38400a4ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7ecfb0c-0f94-4369-9aef-a2ace6832875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-48&quot;)</value>
      <webElementGuid>8cbeb78a-75f0-4edf-9dd0-6513da6389d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-48']</value>
      <webElementGuid>581a9d31-d31f-4ae0-b60c-a018f8cdbbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>6ffb06b0-1d05-43a7-afe0-41cf48eb2b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>95ccaf63-2450-4fb3-9ac8-f380acb1d5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-48' and @type = 'text']</value>
      <webElementGuid>f1208b01-7411-42ff-ad37-0c74f531dcc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
