<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DoB</name>
   <tag></tag>
   <elementGuidId>5c678714-3213-4932-8f79-b65f2f933c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tanggallahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tanggallahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64194ece-01f6-4918-9732-f82d364ad8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>e16dd22d-c229-4c43-a681-d33b0adae0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tanggallahir</value>
      <webElementGuid>868acea4-7509-4735-a731-2eb85e6d26d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>dd31ef7a-f20a-4dbf-90a7-a8eff5c712ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tanggallahir&quot;)</value>
      <webElementGuid>5a4e5f6c-a8c4-4c68-baad-37987d6cc430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tanggallahir']</value>
      <webElementGuid>0dd8c70f-fb78-4373-a5d3-2761c101fad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>7f574523-e4a9-4646-8a15-b59dab75112f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>da575798-c6b0-4003-b8ee-ecb6af802c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'date' and @id = 'tanggallahir' and @type = 'date']</value>
      <webElementGuid>7309a4b4-fa52-4564-b3e8-7c2cf2ec19bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
