<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Name</name>
   <tag></tag>
   <elementGuidId>e93d2608-2abb-4fd5-9660-61bd96eaae51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b6375cb-ad24-49e9-bb31-885acdcb1266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namalengkap</value>
      <webElementGuid>b6209159-fe85-467d-b9c5-53f3b4e2f0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>6d992e85-87eb-452d-853f-4cfcf02e2a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-9</value>
      <webElementGuid>b294aba7-07ef-45af-b402-62272aa0eb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30d50ef6-6818-4e2c-8c64-0b38f6ef3ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-9&quot;)</value>
      <webElementGuid>da51e5e2-8756-4741-88ca-eb2e570683d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-9']</value>
      <webElementGuid>73437eac-fa43-4bef-9396-2a7e28b51235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>b50b5cd1-ad08-4bcf-a893-f976deb99965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d91f7d06-149a-4199-a855-fd2ac3c88de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'namalengkap' and @id = 'input-9' and @type = 'text']</value>
      <webElementGuid>bee82fd2-f898-4991-aba8-1d3d97270fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
