<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account Number</name>
   <tag></tag>
   <elementGuidId>c1a5f240-92ae-4b75-af7a-e0df1788f5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-82</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-82']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc9016a0-bc66-4ec7-86b4-add50742a320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-82</value>
      <webElementGuid>a1fc8c67-becf-4534-8765-d11043dd77f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f8c5920-8256-4efe-95f2-3a16c7febeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-82&quot;)</value>
      <webElementGuid>ecfa86da-47b1-4f29-914d-2eb01301089a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-82']</value>
      <webElementGuid>a3c2d623-25cb-45c0-92f7-bb506f2c21b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>b57792e0-01bd-4f62-bb77-dfd5293bfcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>9dd335d9-51f8-4fc2-a924-34997a84e5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-82' and @type = 'text']</value>
      <webElementGuid>9b375cd2-7a4f-4648-ab42-6fea6f494dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
