<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank Name</name>
   <tag></tag>
   <elementGuidId>b781223d-cb7d-4f12-9cfb-ab1605ce5e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-79</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-79']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>188bfe32-8e2d-417b-a960-f548882c489d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-79</value>
      <webElementGuid>4bb0b417-1d2c-47c4-aa58-aaa12aaf9ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9047f36f-6582-48f8-94e0-b4cdbbe23f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-79&quot;)</value>
      <webElementGuid>52a8d6da-683e-488c-a2bb-a09b4b6991a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-79']</value>
      <webElementGuid>3249355e-c933-4791-a94a-3b8ffbc76083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>2d34027b-5950-41fd-a30e-2ff52154113d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>0ec09b1d-649e-458b-9fd9-4cf2e0a5b6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-79' and @type = 'text']</value>
      <webElementGuid>9d058c54-a0bf-4339-bdb7-4e586d64d5e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
