<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Owner</name>
   <tag></tag>
   <elementGuidId>796ec039-8d09-4ba0-9261-64c47fecd4e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-85</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-85']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a26fec1e-5ee3-4a0d-b63a-e1fff7355101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-85</value>
      <webElementGuid>48503044-71d4-4b4e-9157-24ff767965c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b48a044d-52ea-4b8c-a4ce-bf459ca31e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-85&quot;)</value>
      <webElementGuid>90aadb96-1d94-4c4c-afc0-a9f4f336e10a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-85']</value>
      <webElementGuid>243b635a-6c81-40f2-9ed8-79aedc9cdcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div/div/div[4]/div/div/div/div/input</value>
      <webElementGuid>43d10305-813f-48a7-8b6a-7175b1cf394c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>8c3aac24-cf2c-40d3-9ad2-5afc21569113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-85' and @type = 'text']</value>
      <webElementGuid>5b8d4f8e-c3a5-4aa2-bcab-3e5a318c65f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
