<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chart</name>
   <tag></tag>
   <elementGuidId>d1cca80c-fd13-4693-a82d-7a0340071789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.grafik.order-4.pa-2 > div.mt-4.v-card.v-sheet.theme--light > div.mx-auto.v-sheet.theme--light.white > div.v-progress-circular.chart.v-progress-circular--visible > svg > circle.v-progress-circular__overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>30a45a1c-ce09-4ef2-b129-f71cbd98b846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>0b4f6080-3fc4-4b38-a42d-961e8b63a7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>43.10880829015544</value>
      <webElementGuid>6eb7033b-26b1-462b-8b40-18036e4077e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>43.10880829015544</value>
      <webElementGuid>36417189-0c59-4497-9d6e-c11a6584337f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>fde4c463-a483-4da5-8e58-466e61a245c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>3.10880829015544</value>
      <webElementGuid>3e71d773-ec6a-491b-bb90-f3defc056f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dasharray</name>
      <type>Main</type>
      <value>125.664</value>
      <webElementGuid>9cb5291a-5b14-4473-a066-af83317b2f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dashoffset</name>
      <type>Main</type>
      <value>80.4247719318987px</value>
      <webElementGuid>7faa2a55-6c3a-40c5-ac12-b5bb9c170ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-progress-circular__overlay</value>
      <webElementGuid>ec932774-510d-4d76-820e-fe914ea4cc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex justify-center mb-6&quot;]/div[@class=&quot;grafik order-4 pa-2&quot;]/div[@class=&quot;mt-4 v-card v-sheet theme--light&quot;]/div[@class=&quot;mx-auto v-sheet theme--light white&quot;]/div[@class=&quot;v-progress-circular chart v-progress-circular--visible&quot;]/svg[1]/circle[@class=&quot;v-progress-circular__overlay&quot;]</value>
      <webElementGuid>5e95af08-1c8c-4d70-a4e8-50dfea1979b0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
