<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <elementGuidId>fd4ab245-5a76-45da-8ecf-f9ca5e0c3954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-48']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-48</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a50a3869-e2d8-4847-abf9-2365cdeb03ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-48</value>
      <webElementGuid>4c164bff-2e4b-4dca-9459-717125022106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90087fbd-0ea7-4fd6-b24e-b84c1b1bf6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-48&quot;)</value>
      <webElementGuid>1cdeb136-89da-44b0-84d3-79e6932cb9e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-48']</value>
      <webElementGuid>286ce3b9-e81a-4fcb-86bd-2c0a6add9e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>ad73cd4b-2e44-4759-a066-3af09bb399ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>755d4a21-0ee0-4106-98fe-f996d0eceaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-48' and @type = 'text']</value>
      <webElementGuid>b7fdea28-d6bd-4846-aaae-13a3db7d14b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
