<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date</name>
   <tag></tag>
   <elementGuidId>32167fa5-4fa2-4289-b698-9fb42ee09791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-59']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-59</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83696e6e-309e-4978-a48c-e801be71b554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-59</value>
      <webElementGuid>7ff9607e-a165-42c4-93d8-456cbef3226d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>05182ce4-ee05-4146-bd9d-ed188b6a7de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-59&quot;)</value>
      <webElementGuid>bd1ac91b-0cc3-4649-845c-5bfe69b6a30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-59']</value>
      <webElementGuid>8ee90ca5-cf31-471c-9a43-991ae034f23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div[2]/form/div[4]/div/div/div/input</value>
      <webElementGuid>1d2448f8-f807-4872-98b3-70ad20cbe13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>79182aa9-9f60-4d61-9d40-40a20a746f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-59' and @type = 'date']</value>
      <webElementGuid>8f9fa131-dbde-4ace-a476-1567f1f6febd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
